"""`opsci map build`: write map/graph.md, its image map/graph.svg (and .png) and
map/dead_ends.md from the node headers."""

from __future__ import annotations

import fnmatch
import subprocess
from pathlib import Path, PurePosixPath

import yaml

from . import graphdraw, nodetable, results, tasks
from .nodes import (DEAD_STATUSES, SUBROOTS, Node, Problem, ScanResult, default_privacy, display_type,
                    graph_root, is_task_context, is_task_plan, is_verification, list_files, scan,
                    strictest)

BANNER = "<!-- GENERATED by `opsci map build` from the node headers. Do not edit this file; edit the headers. -->"


def _link(path: str) -> str:
    """Link from map/ to a node file."""
    return "../" + path


def _ref(n: Node, linked) -> str:
    """The node's id, linked to its file unless ``linked`` is a set of paths without it."""
    if linked is not None and n.path not in linked:
        return f"{n.id} (not published)"
    return f"[{n.id}]({_link(n.path)})"


def _task_map(n: Node) -> str | None:
    """The path of a task's map.md, or None if the node is not a task context."""
    return n.path.rsplit("/", 1)[0] + "/map.md" if is_task_context(n.path) else None


def _map_ref(n: Node, linked) -> str:
    """A link to the task's map, where the node is a task and the map is linked."""
    m = _task_map(n)
    if m is None or (linked is not None and m not in linked):
        return ""
    return f" · [map]({_link(m)})"


def _cell(text) -> str:
    return str(text or "").replace("|", "\\|").replace("\n", " ")


def _subroot(n: Node) -> str | None:
    first = n.path.split("/", 1)[0]
    return first if first in SUBROOTS else None


def _graph_nodes(nodes: list[Node]) -> tuple[list[Node], list[Node]]:
    """The nodes the project graph draws, sorted, and the results it leaves to the claims graph."""
    in_claims = [n for n in nodes if n.get("type") == "result" and results.results_dir(n.path)]
    return sorted((n for n in nodes if n not in in_claims), key=lambda n: n.id), in_claims


def _links(nodes: list[Node], ids: set[str]) -> list[tuple[str, str, str]]:
    """The edges between ``ids`` other than dependencies, as (from, to, kind): an old node to
    the node that superseded it, a node to the verification task that verified it, and each
    related pair once."""
    out = []
    for n in nodes:
        out += [(s, n.id, "superseded") for s in n.get("supersedes", []) or [] if s in ids]
        out += [(v, n.id, "verified") for v in n.get("verifies", []) or [] if v in ids]
    out += sorted({(*sorted((n.id, r)), "related") for n in nodes for r in n.get("related", []) or [] if r in ids})
    return out


def graph_drawing(nodes: list[Node], unpublished=frozenset()) -> dict | None:
    """The drawing of the project graph (``graphdraw``), or None if it has no nodes. The
    nodes whose ids are in ``unpublished`` are labelled "not published"."""
    nodes, _ = _graph_nodes(nodes)
    if not nodes:
        return None
    ids = {n.id for n in nodes}
    cards = [{"id": n.id, "title": str(n.get("title") or ""), "meta": f"{display_type(n)} · {n.get('status')}",
              "status": n.get("status"), "box": _subroot(n), "verification": is_verification(n),
              **({"unpublished": True} if n.id in unpublished else {})}
             for n in nodes]
    boxes = [{"id": b, "kicker": b, "title": "ideas, not yet project work", "style": "brainstorm"}
             for b in sorted({b for b in map(_subroot, nodes) if b})]
    edges = [(d, n.id, "dep") for n in nodes for d in n.get("depends_on", []) or [] if d in ids]
    edges = graphdraw.transitive_reduction(edges + _links(nodes, ids))
    return graphdraw.drawing(cards, boxes, edges, "used by")


def render_graph(nodes: list[Node], linked: set[str] | None = None) -> str:
    """The graph of ``nodes``. Edges to ids outside ``nodes`` are left out, so a graph of a
    subset (the published nodes) names nothing outside it. Nodes under a sub-root
    (``brainstorm/``) are drawn in a box of their own. With ``linked`` (a set of paths), only
    those nodes link to their files; the others are named without a link. Results in a
    results directory are left out: the claims graph (``results.render_claims``) draws them.
    The picture is ``graph.svg`` beside this file (``graph_drawing``); the text lists every
    edge it draws."""
    nodes, in_claims = _graph_nodes(nodes)
    ids = {n.id for n in nodes}
    out = [BANNER, "", "# Project graph", ""]
    if not nodes:
        out += ["No nodes yet. A node is any document with a node header (see `tasks/README.md`).", ""]
        return "\n".join(out)
    out += [
        "Each card is a node; its colour shows the status. An arrow from A to B means B depends on",
        "A; an arrow that a longer path of arrows already implies is left out (the table lists",
        "every dependency). Dashed arrows point from a node to the node that superseded it, and",
        "from a node to the verification task that verified it. Dotted lines join related nodes.",
    ]
    if any(map(is_verification, nodes)):
        out.append("Cards with a double border are verification tasks (audits, checks and adverse "
                   "reviews of finished work).")
    boxes = sorted({b for b in map(_subroot, nodes) if b})
    if boxes:
        out.append("The nodes in the " + ", ".join(f"`{b}`" for b in boxes) +
                   " box are ideas under that directory, not yet project work.")
    if in_claims:
        out.append(f"The {len(in_claims)} results in `results/` directories, and what they rest on, are in "
                   "[the claims graph](claims.md).")
    out += ["", "![Project graph](graph.svg)", "",
            "## Nodes", "", "| id | title | type | status | verification | depends on | summary |",
            "|---|---|---|---|---|---|---|"]
    for n in nodes:
        deps = ", ".join(f"`{d}`" for d in n.get("depends_on", []) or [] if d in ids)
        out.append(
            f"| {_ref(n, linked)}{_map_ref(n, linked)} | {_cell(n.get('title'))} | {display_type(n)} | {n.get('status')} | "
            f"{n.get('verification', 'unverified')} | {deps} | {_cell(n.get('summary'))} |"
        )
    out.append("")
    out += results.link_lines(_links(nodes, ids))
    return "\n".join(out)


def render_dead_ends(nodes: list[Node], linked: set[str] | None = None) -> str:
    dead = sorted((n for n in nodes if n.get("status") in DEAD_STATUSES), key=lambda n: n.id)
    superseded_by: dict[str, list[str]] = {}
    for n in nodes:
        for s in n.get("supersedes", []) or []:
            superseded_by.setdefault(s, []).append(n.id)
    out = [BANNER, "", "# Dead ends", "",
           "Every node that failed, was superseded or was abandoned, with the reason in one line.",
           "These routes are recorded so that nobody has to try them again.", ""]
    if not dead:
        out += ["None yet.", ""]
        return "\n".join(out)
    out += ["| id | type | status | why | superseded by |", "|---|---|---|---|---|"]
    for n in dead:
        by = ", ".join(sorted(superseded_by.get(n.id, [])))
        out.append(f"| {_ref(n, linked)} | {display_type(n)} | {n.get('status')} | {_cell(n.get('summary'))} | {by} |")
    out.append("")
    return "\n".join(out)


def outputs(all_nodes: list[Node], root_has, linked: set[str] | None = None,
            bib: dict[str, str] | None = None) -> dict[str, str]:
    """The generated map files: the project map of every node, and for each sub-root that
    exists (``root_has(name)``) a map of its nodes alone, with paths relative to it; then the
    claims graph and the results pages (``results.outputs``). ``bib``: the titles of the
    keys in citations/used.bib."""
    out = {"map/graph.md": render_graph(all_nodes, linked),
           "map/dead_ends.md": render_dead_ends(all_nodes, linked)}
    for sub in SUBROOTS:
        if not root_has(sub):
            continue
        pre = sub + "/"
        mine = [Node(n.path[len(pre):], n.header) for n in all_nodes if n.path.startswith(pre)]
        sub_linked = None if linked is None else {p[len(pre):] for p in linked if p.startswith(pre)}
        out[f"{sub}/map/graph.md"] = render_graph(mine, sub_linked)
        out[f"{sub}/map/dead_ends.md"] = render_dead_ends(mine, sub_linked)
    out.update(results.outputs(all_nodes, root_has, linked, bib))
    return out


def drawings(all_nodes: list[Node], root_has, bib: dict[str, str] | None = None,
             unpublished=frozenset()) -> dict[str, dict]:
    """The graph images beside the map files, as path without suffix -> drawing
    (``graphdraw``): the project graph and the claims graph, and the same for each sub-root
    that exists. A graph with nothing in it has no image. The nodes whose ids are in
    ``unpublished`` are labelled "not published"."""
    out = {"map/graph": graph_drawing(all_nodes, unpublished),
           "map/claims": results.claims_drawing(all_nodes, bib, unpublished)}
    for sub in SUBROOTS:
        if root_has(sub):
            pre = sub + "/"
            out[f"{sub}/map/graph"] = graph_drawing([Node(n.path[len(pre):], n.header) for n in all_nodes
                                                     if n.path.startswith(pre)], unpublished)
            out[f"{sub}/map/claims"] = results.claims_drawing([n for n in all_nodes if n.path.startswith(pre)], bib,
                                                              unpublished)
    return {k: v for k, v in out.items() if v}


def draw(root: Path, draws: dict[str, dict], res: ScanResult, only: set[str] | None = None) -> list[str]:
    """Draw every image of ``draws`` under ``root`` that is out of date (with ``only``, a set
    of paths, only the images in it). Returns the images drawn; a failure is a warning."""
    done = []
    for base, d in draws.items():
        if (only is not None and f"{base}.svg" not in only) or graphdraw.is_current(root / base, d):
            continue
        try:
            graphdraw.render(d, root / base)
            done.append(f"{base}.svg")
        except (graphdraw.DrawError, OSError, subprocess.SubprocessError) as exc:
            res.warnings.append(Problem(f"{base}.svg", f"graph image not drawn: {exc}"))
    return done


def check_verification_privacy(root: Path, res: ScanResult) -> None:
    """Warn when a verification task is less private than a node it verifies: its default
    is the strictest tier among them."""
    default = default_privacy(root)
    ids = res.by_id()
    for n in filter(is_verification, res.nodes):
        targets = [ids[t] for t in n.get("verifies") if t in ids]
        want = strictest(t.get("privacy", default) for t in targets)
        have = n.get("privacy", default)
        if strictest([want, have]) != have:
            res.warnings.append(Problem(n.path, f"privacy is {have}, but it verifies {want} work; "
                                        f"set privacy: {want} unless the user chose otherwise"))


def check_manifest(root: Path, res: ScanResult) -> None:
    """Every manifest entry with a `type` must be covered by a node of that type."""
    mpath = root / "publish" / "manifest.yaml"
    if not mpath.exists():
        return
    rel = "publish/manifest.yaml"
    try:
        manifest = yaml.safe_load(mpath.read_text()) or {}
    except yaml.YAMLError as exc:
        res.errors.append(Problem(rel, f"not valid YAML: {exc}".splitlines()[0]))
        return
    entries = manifest.get("include") or []
    if not isinstance(entries, list):
        res.errors.append(Problem(rel, "include: must be a list"))
        return
    files = list_files(root)
    nodes_by_path = {n.path: n for n in res.nodes}
    for entry in entries:
        if not isinstance(entry, dict) or "path" not in entry:
            res.errors.append(Problem(rel, f"include entry {entry!r} has no 'path'"))
            continue
        want = entry.get("type")
        if want is None:
            continue
        pattern = str(entry["path"]).rstrip("/")
        matched = [f for f in files if fnmatch.fnmatchcase(f, pattern) or f.startswith(pattern + "/")]
        if not matched:
            res.errors.append(Problem(rel, f"entry '{entry['path']}' (type {want}) matches no file"))
            continue
        for f in matched:
            if not _covered(f, want, nodes_by_path):
                res.errors.append(Problem(rel, f"published {want} '{f}' is not in the graph (no {want} node header in it or a node.yaml above it)"))


def _covered(path: str, want: str, nodes_by_path: dict[str, Node]) -> bool:
    n = nodes_by_path.get(path)
    if n is not None and n.get("type") == want:
        return True
    parent = PurePosixPath(path).parent
    while True:
        cand = (parent / "node.yaml").as_posix() if str(parent) != "." else "node.yaml"
        n = nodes_by_path.get(cand)
        if n is not None and n.get("type") == want:
            return True
        if str(parent) == ".":
            return False
        parent = parent.parent


def node_tables(root: Path) -> dict[str, str]:
    """Every task context.md and plan.md whose node table is missing or out of date, with its
    new text."""
    out = {}
    for rel in list_files(root):
        if is_task_context(rel) or is_task_plan(rel):
            try:
                text = (root / rel).read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue  # the scan reports it
            new = nodetable.refresh(text)
            if new != text:
                out[rel] = new
    return out


def task_maps(root: Path, res: ScanResult) -> dict[str, str]:
    """A starting map.md for every task that has none. An existing map is never rewritten:
    the main agent keeps it."""
    out = {}
    for n in res.nodes:
        m = _task_map(n)
        if m is not None and not (root / m).exists():
            out[m] = tasks.MAP_BODY.format(title=n.get("title"), id=n.id)
    return out


def build(root: Path, check: bool = False) -> tuple[ScanResult, list[str]]:
    """Scan, check and (unless check) write. Returns the scan and the stale generated files:
    the maps, the claims graph and results pages, the graph images (``drawings``), the task
    files whose node table is out of date, and the missing task maps. A
    sub-root (``brainstorm``) builds the project around it: one graph covers both."""
    root, _ = graph_root(Path(root))
    res = scan(root)
    check_manifest(root, res)
    check_verification_privacy(root, res)
    results.check(root, res)
    files = outputs(res.nodes, lambda sub: (root / sub).is_dir(), bib=results.read_bib(root))
    files.update(node_tables(root))
    files.update(task_maps(root, res))
    from .publish import unpublished_nodes  # local import: publish imports this module
    draws = drawings(res.nodes, lambda sub: (root / sub).is_dir(), results.read_bib(root),
                     unpublished_nodes(root, res.nodes))
    stale = []
    for rel, text in files.items():
        p = root / rel
        if not p.exists() or p.read_text() != text:
            stale.append(rel)
    stale += [f"{b}.svg" for b, d in draws.items() if not graphdraw.is_current(root / b, d)]
    if not check and not res.errors:
        for rel, text in files.items():
            p = root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
        draw(root, draws, res)
    return res, stale
