"""`opsci map build`: write map/graph.md and map/dead_ends.md from the node headers."""

from __future__ import annotations

import fnmatch
from pathlib import Path, PurePosixPath

import yaml

from . import nodetable, tasks
from .nodes import (DEAD_STATUSES, SUBROOTS, Node, Problem, ScanResult, graph_root, is_task_context,
                    is_task_plan, list_files, scan)

BANNER = "<!-- GENERATED by `opsci map build` from the node headers. Do not edit this file; edit the headers. -->"

STATUS_STYLE = {
    "active": "fill:#dbeafe,stroke:#1d4ed8",
    "done": "fill:#dcfce7,stroke:#15803d",
    "paused": "fill:#fef9c3,stroke:#a16207",
    "failed": "fill:#fee2e2,stroke:#b91c1c",
    "superseded": "fill:#e5e7eb,stroke:#4b5563",
    "abandoned": "fill:#e5e7eb,stroke:#4b5563,stroke-dasharray:4",
}


def _mid(node_id: str) -> str:
    return "n_" + node_id.replace("-", "_")


def _label(text: str) -> str:
    return text.replace('"', "#quot;").replace("\n", " ")


def _link(path: str) -> str:
    """Link from map/ to a node file."""
    return "../" + path


def _ref(n: Node, linked) -> str:
    """The node's id, linked to its file unless ``linked`` is a set of paths without it."""
    if linked is not None and n.path not in linked:
        return f"{n.id} (not published)"
    return f"[{n.id}]({_link(n.path)})"


def _task_map(n: Node) -> str | None:
    """The path of a task's map.md, or None if the node is not a task context."""
    return n.path.rsplit("/", 1)[0] + "/map.md" if is_task_context(n.path) else None


def _map_ref(n: Node, linked) -> str:
    """A link to the task's map, where the node is a task and the map is linked."""
    m = _task_map(n)
    if m is None or (linked is not None and m not in linked):
        return ""
    return f" · [map]({_link(m)})"


def _cell(text) -> str:
    return str(text or "").replace("|", "\\|").replace("\n", " ")


def _subroot(n: Node) -> str | None:
    first = n.path.split("/", 1)[0]
    return first if first in SUBROOTS else None


def render_graph(nodes: list[Node], linked: set[str] | None = None) -> str:
    """The graph of ``nodes``. Edges to ids outside ``nodes`` are left out, so a graph of a
    subset (the published nodes) names nothing outside it. Nodes under a sub-root
    (``brainstorm/``) are drawn in a box of their own. With ``linked`` (a set of paths), only
    those nodes link to their files; the others are named without a link."""
    nodes = sorted(nodes, key=lambda n: n.id)
    ids = {n.id for n in nodes}
    out = [BANNER, "", "# Project graph", ""]
    if not nodes:
        out += ["No nodes yet. A node is any document with a node header (see `tasks/README.md`).", ""]
        return "\n".join(out)
    out += [
        "Arrows: `A --> B` means B depends on A. Dotted arrows point from the new node to the",
        "node it supersedes. Plain lines join related nodes. Colour shows the status.",
    ]
    boxes = sorted({b for b in map(_subroot, nodes) if b})
    if boxes:
        out.append("The nodes in the " + ", ".join(f"`{b}`" for b in boxes) +
                   " box are ideas under that directory, not yet project work.")
    out += ["", "```mermaid", "flowchart LR"]
    for box in [None] + boxes:
        if box:
            out.append(f'  subgraph {box}["{box}"]')
        for n in nodes:
            if _subroot(n) == box:
                out.append(f'  {"  " if box else ""}{_mid(n.id)}["{_label(n.id)}: {_label(n.get("title"))}'
                           f'<br/>{n.get("type")} · {n.get("status")}"]')
        if box:
            out.append("  end")
    for n in nodes:
        for d in n.get("depends_on", []) or []:
            if d in ids:
                out.append(f"  {_mid(d)} --> {_mid(n.id)}")
        for s in n.get("supersedes", []) or []:
            if s in ids:
                out.append(f"  {_mid(n.id)} -.->|supersedes| {_mid(s)}")
    pairs = sorted({tuple(sorted((n.id, r))) for n in nodes for r in n.get("related", []) or [] if r in ids})
    for a, b in pairs:  # each related pair once, whichever side lists it
        out.append(f"  {_mid(a)} --- {_mid(b)}")
    for status, style in STATUS_STYLE.items():
        members = [_mid(n.id) for n in nodes if n.get("status") == status]
        if members:
            out.append(f"  classDef {status} {style}")
            out.append(f"  class {','.join(members)} {status}")
    out += ["```", "", "## Nodes", "", "| id | type | status | verification | summary |", "|---|---|---|---|---|"]
    for n in nodes:
        out.append(
            f"| {_ref(n, linked)}{_map_ref(n, linked)} | {n.get('type')} | {n.get('status')} | "
            f"{n.get('verification', 'unverified')} | {_cell(n.get('summary'))} |"
        )
    out.append("")
    return "\n".join(out)


def render_dead_ends(nodes: list[Node], linked: set[str] | None = None) -> str:
    dead = sorted((n for n in nodes if n.get("status") in DEAD_STATUSES), key=lambda n: n.id)
    superseded_by: dict[str, list[str]] = {}
    for n in nodes:
        for s in n.get("supersedes", []) or []:
            superseded_by.setdefault(s, []).append(n.id)
    out = [BANNER, "", "# Dead ends", "",
           "Every node that failed, was superseded or was abandoned, with the reason in one line.",
           "These routes are recorded so that nobody has to try them again.", ""]
    if not dead:
        out += ["None yet.", ""]
        return "\n".join(out)
    out += ["| id | type | status | why | superseded by |", "|---|---|---|---|---|"]
    for n in dead:
        by = ", ".join(sorted(superseded_by.get(n.id, [])))
        out.append(f"| {_ref(n, linked)} | {n.get('type')} | {n.get('status')} | {_cell(n.get('summary'))} | {by} |")
    out.append("")
    return "\n".join(out)


def outputs(all_nodes: list[Node], root_has, linked: set[str] | None = None) -> dict[str, str]:
    """The generated map files: the project map of every node, and for each sub-root that
    exists (``root_has(name)``) a map of its nodes alone, with paths relative to it."""
    out = {"map/graph.md": render_graph(all_nodes, linked),
           "map/dead_ends.md": render_dead_ends(all_nodes, linked)}
    for sub in SUBROOTS:
        if not root_has(sub):
            continue
        pre = sub + "/"
        mine = [Node(n.path[len(pre):], n.header) for n in all_nodes if n.path.startswith(pre)]
        sub_linked = None if linked is None else {p[len(pre):] for p in linked if p.startswith(pre)}
        out[f"{sub}/map/graph.md"] = render_graph(mine, sub_linked)
        out[f"{sub}/map/dead_ends.md"] = render_dead_ends(mine, sub_linked)
    return out


def check_manifest(root: Path, res: ScanResult) -> None:
    """Every manifest entry with a `type` must be covered by a node of that type."""
    mpath = root / "publish" / "manifest.yaml"
    if not mpath.exists():
        return
    rel = "publish/manifest.yaml"
    try:
        manifest = yaml.safe_load(mpath.read_text()) or {}
    except yaml.YAMLError as exc:
        res.errors.append(Problem(rel, f"not valid YAML: {exc}".splitlines()[0]))
        return
    entries = manifest.get("include") or []
    if not isinstance(entries, list):
        res.errors.append(Problem(rel, "include: must be a list"))
        return
    files = list_files(root)
    nodes_by_path = {n.path: n for n in res.nodes}
    for entry in entries:
        if not isinstance(entry, dict) or "path" not in entry:
            res.errors.append(Problem(rel, f"include entry {entry!r} has no 'path'"))
            continue
        want = entry.get("type")
        if want is None:
            continue
        pattern = str(entry["path"]).rstrip("/")
        matched = [f for f in files if fnmatch.fnmatchcase(f, pattern) or f.startswith(pattern + "/")]
        if not matched:
            res.errors.append(Problem(rel, f"entry '{entry['path']}' (type {want}) matches no file"))
            continue
        for f in matched:
            if not _covered(f, want, nodes_by_path):
                res.errors.append(Problem(rel, f"published {want} '{f}' is not in the graph (no {want} node header in it or a node.yaml above it)"))


def _covered(path: str, want: str, nodes_by_path: dict[str, Node]) -> bool:
    n = nodes_by_path.get(path)
    if n is not None and n.get("type") == want:
        return True
    parent = PurePosixPath(path).parent
    while True:
        cand = (parent / "node.yaml").as_posix() if str(parent) != "." else "node.yaml"
        n = nodes_by_path.get(cand)
        if n is not None and n.get("type") == want:
            return True
        if str(parent) == ".":
            return False
        parent = parent.parent


def node_tables(root: Path) -> dict[str, str]:
    """Every task context.md and plan.md whose node table is missing or out of date, with its
    new text."""
    out = {}
    for rel in list_files(root):
        if is_task_context(rel) or is_task_plan(rel):
            try:
                text = (root / rel).read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue  # the scan reports it
            new = nodetable.refresh(text)
            if new != text:
                out[rel] = new
    return out


def task_maps(root: Path, res: ScanResult) -> dict[str, str]:
    """A starting map.md for every task that has none. An existing map is never rewritten:
    the main agent keeps it."""
    out = {}
    for n in res.nodes:
        m = _task_map(n)
        if m is not None and not (root / m).exists():
            out[m] = tasks.MAP_BODY.format(title=n.get("title"), id=n.id)
    return out


def build(root: Path, check: bool = False) -> tuple[ScanResult, list[str]]:
    """Scan, check and (unless check) write. Returns the scan and the stale generated files:
    the maps, the task files whose node table is out of date, and the missing task maps. A
    sub-root (``brainstorm``) builds the project around it: one graph covers both."""
    root, _ = graph_root(Path(root))
    res = scan(root)
    check_manifest(root, res)
    files = outputs(res.nodes, lambda sub: (root / sub).is_dir())
    files.update(node_tables(root))
    files.update(task_maps(root, res))
    stale = []
    for rel, text in files.items():
        p = root / rel
        if not p.exists() or p.read_text() != text:
            stale.append(rel)
    if not check and not res.errors:
        for rel, text in files.items():
            p = root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
    return res, stale
